service: readysetvote

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  version:
    handler: server/handler.version
    events:
      - http:
          method: get
          path: version
